CREATE TABLE `combination_profit` (
  `combination` VARCHAR(50) DEFAULT NULL,
  `init_big` DECIMAL(30, 10) DEFAULT NULL,
  `init_small` DECIMAL(30, 10) DEFAULT NULL,
  `init_bnb` DECIMAL(30, 10) DEFAULT NULL,
  `init_huobi` DECIMAL(30, 10) DEFAULT NULL,
  `yes_big` DECIMAL(30, 10) DEFAULT NULL,
  `yes_small` DECIMAL(30, 10) DEFAULT NULL,
  `yes_bnb` DECIMAL(30, 10) DEFAULT NULL,
  `yes_huobi` DECIMAL(30, 10) DEFAULT NULL,
  `now_big` DECIMAL(30, 10) DEFAULT NULL,
  `now_small` DECIMAL(30, 10) DEFAULT NULL,
  `now_bnb` DECIMAL(30, 10) DEFAULT NULL,
  `now_huobi` DECIMAL(30, 10) DEFAULT NULL,
  `daily_profit_rate` DECIMAL(30, 10) DEFAULT NULL,
  `total_profit_rate` DECIMAL(30, 10) DEFAULT NULL,
  `daily_profit` DECIMAL(30, 10) DEFAULT NULL,
  `total_profit` DECIMAL(30, 10) DEFAULT NULL,
  `no_fee_daily_profit_rate` DECIMAL(30, 10) DEFAULT NULL,
  `no_fee_total_profit_rate` DECIMAL(30, 10) DEFAULT NULL,
  `no_fee_daily_profit` DECIMAL(30, 10) DEFAULT NULL,
  `no_fee_total_profit` DECIMAL(30, 10) DEFAULT NULL,
  `log_time` VARCHAR(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
